# DO NOT CHANGE THIS FILE, EDIT CONFIGURATIONS AT application.yml
default: &default
  adapter:  postgresql
  database: 'auto-deploy'
  encoding: unicode
  host:     'localhost'
  password: 'password'
  pool: '5'
  database_username: 'auto-deploy'

development:
  <<: *default
test:
  <<: *default
  database: <%= ENV['DATABASE_DATABASE'] %>
production:
  <<: *default
# DO NOT CHANGE THIS FILE, EDIT CONFIGURATIONS AT application.yml